Vagrant.configure("2") do |config|
  config.vm.box = "test_box_py"

  # Создаем виртуальную машину
  config.vm.provider "virtualbox" do |vb|
    vb.name = "test-box-py"
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.hostname = "test-box-py"

  # Устанавливаем необходимое ПО и библиотеки
  config.vm.provision "update", type: "shell", inline: "echo update list repo; apt update"
  config.vm.provision "python3", type: "shell", inline: "echo Installing Python3; apt install -y python3"
  config.vm.provision "python3-pip", type: "shell", inline: "echo Installing PIP for Python3; apt install -y python3-pip" 
  config.vm.provision "pip-psycopg2", type: "shell", inline: "echo Installing psycopg2 library; pip3 install psycopg2"
  

# Копируем файл в виртуальную машину  
  config.vm.synced_folder "./fileshare", "/tmp/vagrant_data"
  
end
